"""menambahkan chatgrup member

Revision ID: 101c65246a1e
Revises: 1ebe78a9fa46
Create Date: 2024-11-16 16:55:31.442050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101c65246a1e'
down_revision = '1ebe78a9fa46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_group_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_room_grup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_group_member')
    # ### end Alembic commands ###
