"""menambahkan field baru di chatroomgrup

Revision ID: 179f4fc1acce
Revises: 101c65246a1e
Create Date: 2024-11-16 17:33:01.745909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179f4fc1acce'
down_revision = '101c65246a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_room_grup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_room_grup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
