"""menambahkan chatroomgrup

Revision ID: 44a54b9090f9
Revises: 23c4e4a43f7a
Create Date: 2024-11-15 10:39:00.472004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a54b9090f9'
down_revision = '23c4e4a43f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room_grup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_room_grup')
    # ### end Alembic commands ###
