""" menambahkam gambar ke chat

Revision ID: 5b70eb7d62c0
Revises: f29476febdf4
Create Date: 2024-11-11 12:53:42.730928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b70eb7d62c0'
down_revision = 'f29476febdf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
